UPDATE Defines Set Value=1.92 WHERE Name='POLICY_COST_EXPONENT';/*2.01*/

UPDATE Defines Set Value=4 Where Name='BASE_CULTURE_PER_GREAT_WORK'; /*2*/
UPDATE Defines Set Value=3 Where Name='BASE_TOURISM_PER_GREAT_WORK'; /*2*/
UPDATE Defines Set Value=-25 Where Name='TOURISM_MODIFIER_DIFFERENT_IDEOLOGIES'; /*-34*/

UPDATE Defines Set Value=2 Where Name='FRIENDS_CULTURE_BONUS_AMOUNT_ANCIENT'; /*3*/
UPDATE Defines Set Value=4 Where Name='FRIENDS_CULTURE_BONUS_AMOUNT_MEDIEVAL'; /*6*/
UPDATE Defines Set Value=8 Where Name='FRIENDS_CULTURE_BONUS_AMOUNT_INDUSTRIAL'; /*13*/
UPDATE Defines Set Value=2 Where Name='ALLIES_CULTURE_BONUS_AMOUNT_ANCIENT'; /*3*/
UPDATE Defines Set Value=4 Where Name='ALLIES_CULTURE_BONUS_AMOUNT_MEDIEVAL'; /*6*/
UPDATE Defines Set Value=8 Where Name='ALLIES_CULTURE_BONUS_AMOUNT_INDUSTRIAL'; /*13*/
/*UPDATE Defines Set Value=4 Where Name='FRIENDS_HAPPINESS_FLAT_BONUS_AMOUNT_INDUSTRIAL'; *//*3*/
/*UPDATE Defines Set Value=2 Where Name='ALLIES_HAPPINESS_FLAT_BONUS_AMOUNT_ANCIENT'; *//*0*/
/*UPDATE Defines Set Value=2 Where Name='ALLIES_HAPPINESS_FLAT_BONUS_AMOUNT_MEDIEVAL'; *//*0*/
/*UPDATE Defines Set Value=2 Where Name='ALLIES_HAPPINESS_FLAT_BONUS_AMOUNT_INDUSTRIAL'; *//*0*/