INSERT INTO Defines
(Name, Value) VALUES
('AMB_AI_RECKLESS_EXPANDER_APPROACH_FRIENDLY_MOD', -30), /*These influence how hard the hit is based on approach*/
('AMB_AI_RECKLESS_EXPANDER_APPROACH_NEUTRAL_MOD', -10),
('AMB_AI_RECKLESS_EXPANDER_APPROACH_GUARDED_MOD', 5),
('AMB_AI_RECKLESS_EXPANDER_APPROACH_HOSTILE_MOD', 20),
('AMB_AI_RECKLESS_EXPANDER_APPROACH_DECEPTIVE_MOD', 5),
('AMB_AI_RECKLESS_EXPANDER_APPROACH_WAR_MOD', 20),
('AMB_AI_RECKLESS_EXPANDER_APPROACH_AFRAID_MOD', -30),
('AMB_AI_RECKLESS_EXPANDER_STRENGTH_MOD', 20), /*If we are deceptive/war add this if target is weak*/
('AMB_AI_RECKLESS_EXPANDER_PERSONALITY_MOD', 30), /*How competitive and forgiving we are has influence (VC-Forgive)/5*this */
('AMB_AI_RECKLESS_EXPANDER_DOF_MOD', -50), /*Dof mod*/
('AMB_AI_RECKLESS_EXPANDER_DENOUNCE_MOD', 30), /*Denounce mod*/
('AMB_AI_RECKLESS_EXPANDER_NEIGHBOURS_MOD', 10), /*Proximity mods*/
('AMB_AI_RECKLESS_EXPANDER_CLOSE_MOD', 0),
('AMB_AI_RECKLESS_EXPANDER_FAR_MOD', -20),
('AMB_AI_RECKLESS_EXPANDER_DISTANT_MOD', -30),
('AMB_AI_RECKLESS_EXPANDER_MOD_APPROACH_MINOR', 105), /*How the expander level influence negative weights*/
('AMB_AI_RECKLESS_EXPANDER_MOD_APPROACH_MAJOR', 115),
('AMB_AI_RECKLESS_EXPANDER_MOD_APPROACH_SEVERE', 130),
('AMB_AI_RECKLESS_EXPANDER_MOD_APPROACH_CRITICAL', 140),
('AMB_AI_WARMONGER_CB_APPROACH_WAR_MOD', 200), /*How having a CB influence war approach in % */
('AMB_AI_WARMONGER_CB_APPROACH_DECEPTIVE_MOD', 200),
('AMB_AI_DEAL_AI_INTEREST', 100),
('AMB_AI_DEAL_HUMAN_INTEREST', 115);

/*UPDATE Units SET Combat=500 WHERE Class='UNITCLASS_ARCHER'; /*For test purposes*/